Repository redhat-developer/vscode-xml, pull requests merged in 2021-06, with the labels that each got.

#497 Optimize images size
  .vscodeignore
  docs/images/CodeLens/DTDElementCodeLens.gif
  docs/images/CodeLens/XSDElementCodeLens.gif
  docs/images/CodeLens/XSDTypeCodeLens.gif
  docs/images/Commands/XMLCommands.png
  docs/images/Extensions/DebugAttachRemote.png
  docs/images/Extensions/DebugConfigurations.png
  docs/images/Extensions/DebugLemMinXExtensionInEclipse.png
  docs/images/Extensions/DebugLemMinXExtensionInVSCode.png
  docs/images/Extensions/DebugMultiRootSetup.png
  docs/images/Extensions/DebugVSCodeXML.png
  docs/images/Extensions/DebugVSCodeXMLSingleRoot.png
  docs/images/Extensions/EclipseRunDebugConfigurations.png
  docs/images/Extensions/EclipseWithLemMinXExtensionOpen.png
  docs/images/Extensions/HitABreakpointVSCode.png
  docs/images/Extensions/InstallVSCodeExtensionForLemMinXExtension.png
  docs/images/Extensions/LaunchVSCodeExtensionForLemMinXExtension.png
  docs/images/Extensions/NewDebugConfiguration.png
  docs/images/Extensions/PackageVSCodeExtensionForLemMinXExtension.png
  docs/images/Extensions/ProjectWindowAndDebugWindow.png
  docs/images/Extensions/ProjectWindowAndDebugWindowSingleRoot.png
  docs/images/Extensions/TerminalInstallVSCodeExtensionForLemMinXExtension.png
  docs/images/Extensions/VSCodeExtensionForLemMinXExtension.png
  docs/images/Features/AutoCloseTagEnd.gif
  docs/images/Features/AutoCloseTagSlash.gif
  docs/images/Features/JumpToClosingTag.gif
  docs/images/Features/JumpToOpeningTag.gif
  docs/images/Features/RenameTag.gif
  docs/images/Features/SelectionRange.gif
  docs/images/Preferences/HoverDocumentationQuickDemo.gif
  docs/images/Symbols/ShowReferencedGrammars.png
  docs/images/Symbols/SymbolsBeansWithIdAttrFilter.png
  docs/images/Symbols/SymbolsPOMWithTextFilter.png
  docs/images/Symbols/SymbolsPOMWithoutFilter.png
  docs/images/Validation/DoctypeError1.png
  docs/images/Validation/DoctypeError2.png
  docs/images/Validation/ExternalEntityResolvingDemonstration.gif
  docs/images/Validation/GenerateXSD.gif
  docs/images/Validation/XMLGrammarError.png
  docs/images/Validation/XMLSyntaxError.png
  docs/images/Validation/XMLSyntaxErrorCodeAction.gif
  docs/images/vscode-xml-maven.gif
  icons/icon128.png
  images/DownloadBinaryArtifacts.png
  images/DownloadBinaryChecks.png
  images/LaunchExtension.png
Labels: enhancement

#508 Added closingBracketNewLine formatting option to package.json
  docs/Formatting.md
  package.json
Labels: enhancement, formatting

#520 Fix extension not starting in vscode < 1.55
  CHANGELOG.md
  package-lock.json
  package.json
Labels: bug, dependencies
