Repository redhat-developer/vscode-xml, pull requests merged in 2022-11, with the labels that each got.

#799 Fix issues reported by npm-audit.
  package-lock.json
  package.json
Labels: dependencies

#800 Add documentation for files.trimTrailingWhitespace setting
  docs/Formatting.md
Labels: documentation

#807 Provide the capability to bind RelaxNG schema
  src/commands/registerCommands.ts
Labels: bug

#811 Add MEI, TEI, SVG as keywords
  package.json
Labels: enhancement

#812 Update vscode-redhat-telemetry to 0.5.2
  USAGE_DATA.md
  package-lock.json
  package.json
Labels: enhancement, dependencies

#814 lemminx logfile: fallback to global storage
  src/extension.ts
Labels: enhancement

#817 Update xml.format.joinContentLines settings documentation
  docs/Formatting.md
Labels: documentation

#826 Add link to blog for 0.22.0 release
  README.md
Labels: documentation
