Repository redhat-developer/vscode-xml, pull requests merged in 2022-10, with the labels that each got.

#779 Fix problem matcher
  .vscode/extensions.json
  .vscode/tasks.json
  package-lock.json
  package.json
  webpack.config.js
Labels: build

#781 RelaxNG compact textmate+language-configuration support
  package.json
  rnc.language-configuration.json
  src/client/xmlClient.ts
  syntaxes/rnc.tmLanguage.json
Labels: enhancement, textmate

#788 Fix syntax coloration with element/attribute which can contains '-'
  syntaxes/rnc.tmLanguage.json
Labels: bug, textmate

#789 Make sure that 'vsce' is installed in nodes that use it.
  Jenkinsfile
Labels: build

#787 RelaxNG documentation
  README.md
  docs/Features.md
  docs/Features/RelaxNGFeatures.md
  docs/README.md
  docs/Validation.md
  docs/images/RelaxNG/GoToTypeDefinitionMenu.png
  docs/images/RelaxNG/GoToTypeDefinitionResult.png
  docs/images/RelaxNG/RelaxNGCompactSyntaxOverview.png
  docs/images/RelaxNG/RelaxNGCompletionAndDocumentation.png
  docs/images/RelaxNG/RelaxNGHoverAndDocumentation.png
  docs/images/RelaxNG/RelaxNGSnippetsSupport.gif
  docs/images/RelaxNG/RelaxNGSupport.gif
  docs/images/RelaxNG/RelaxNGValidation.png
  docs/images/RelaxNG/RelaxNGXMLSyntaxOverview.png
  docs/images/RelaxNG/XMLValidatedWithRelaxNG.png
Labels: documentation

#782 Report only XML syntax error for *.exsd files
  docs/Validation.md
  package.json
Labels: enhancement

#792 Fix relaxng links
  README.md
  docs/Features/RelaxNGFeatures.md
  docs/Validation.md
Labels: documentation
