Repository redhat-developer/vscode-xml, pull requests merged in 2022-09, with the labels that each got.

#774 Suppress validation kinds based on file pattern
  README.md
  docs/Validation.md
  package.json
Labels: enhancement, validation

#776 Update description for joinCDATALines with experimental formatter
  docs/Formatting.md
  package.json
Labels: documentation

#777 Update description for preservedNewLines with experimental formatter
  docs/Formatting.md
  package.json
Labels: documentation

#778 Update description for preserveEmptyContent with experimental formatter
  docs/Formatting.md
  package.json
Labels: dependencies

#780 Update description for emptyElements and joinContentLines
  docs/Formatting.md
  package.json
Labels: documentation

#768 Update badges
  README.md
Labels: documentation
