Repository redhat-developer/vscode-xml, pull requests merged in 2022-07, with the labels that each got.

#725 Add support for pre-releases.
  Jenkinsfile
  gulpfile.js
  package.json
Labels: enhancement, build

#734 Remove darwin-arm64 platform from generic publishing call.
  Jenkinsfile
Labels: bug, build

#737 Update description for enforceQuoteStyle setting with experimental formatter
  docs/Formatting.md
  package.json
Labels: enhancement

#746 Update description for joinCommentLines setting with experimental formatter
  docs/Formatting.md
  package.json
Labels: enhancement

#747 Update Jenkins build scripts for branch renaming
  Jenkinsfile
  README.md
  docs/Extensions.md
  docs/Preferences.md
Labels: documentation, build

#750 Explicitly set 'main' as target branch for cloning of lemminx repo.
  Jenkinsfile
Labels: build
