Repository redhat-developer/vscode-xml, pull requests merged in 2023-01, with the labels that each got.

#852 Fix lint.yaml build status badge
  README.md
Labels: documentation

#847 Declare xml.references settings
  README.md
  docs/Features.md
  docs/Features/XMLReferencesFeatures.md
  docs/images/Features/XMLReferencesWithDocbook.gif
  docs/images/Features/XMLReferencesWithWebXML.gif
  package.json
Labels: documentation

#855 multiple support for xml.references"
  docs/Features/XMLReferencesFeatures.md
  docs/images/Features/XMLReferencesWithTEI.gif
  package.json
Labels: enhancement

#857 React to vsce renaming to @vscode/vsce.
  Jenkinsfile
Labels: build

#858 Also use "@vscode/vsce" in the publish phase.
  Jenkinsfile
Labels: build

#863 Remove reference to repository.engineering.redhat.com
  package-lock.json
Labels: dependencies

#862 Support identation for XML contributed languages
  src/extension.ts
Labels: bug
